spring:
  config:
    import: optional:dotenv:.env
  application:
    name: ai-code-review-assistant

  datasource:
    url: ${NEON_DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${NEON_DB_USERNAME}
    password: ${NEON_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  graphql:
    graphiql:
      enabled: true

  ai:
    openai:
      api-key: ${GROK_API_KEY:dummy-api-key}
      base-url: https://api.xai.com/v1
      chat:
        options:
          model: grok-beta
          temperature: 0.2
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
          temperature: 0.2
